language: python

python:
  - "3.6"

service:
  - postgresql

addons:
  postgresql: '9.6'

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls

before_script:
  - python manage.py collectstatic
  - export DB_NAME="flightbooking"
  - psql -c 'create database flightbooking;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate
  - export TIME_DELTA=100

script:
  # - python manage.py test flightbooking/apps
  - coverage run --source=. manage.py test flightbooking/apps
  - coverage report --omit=*/migrations/*,*/tests/*,*wsgi.py*,*celery.py*,*locustMock.py*,*locustfile.py*

after_script:
  - coveralls
